name = "background-remover"
type = "python"

account_id = "6985a0a8491427aee57107f93794a7fa"
workers_dev = true
compatibility_date = "2023-10-07"

[[routable]]
pattern = "bg-remover-8lb.pages.dev" #domain of my tool
