name = "background-remover"
type = "python"

account_id = "YOUR_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2023-10-07"

[[routable]]
pattern = "your-worker-subdomain.cloudflareworkers.com/*"
